version: '2.0'
services:
  bot:
    build: bot
    container_name: relaybot
    restart: always
    env_file:
      env.env
    networks:
      - system-proxy_default


networks:
  system-proxy_default:
    external: true