version: '2.0'
services:
  bot:
    build:
      context: ./
      dockerfile: bot/Dockerfile-dev
    container_name: relaybot
    restart: always
    volumes:
      - ./bot:/usr/src/app
    env_file:
      env.env
    depends_on:
      - redis
    networks:
      - system-proxy_default
      - relaybot

  redis:
    image: redis
    command: --appendonly yes
    restart: always
    networks:
      - relaybot

networks:
  relaybot:
    driver: bridge
  system-proxy_default:
    external: true
